version: '3.8'
services:
  pgdb:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rootdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # This is optional setup
  # pgadmin:
  #   depends_on:
  #     - db
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  
  api-server:
    depends_on:
      - pgdb
    build: ./
    image: qrlyf-core
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/app
    ports:
      - 8000:8000
    env_file:
      - ./environments/dev.env
