version: '3.8'
services:
  db:
    container_name: postgres-db
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: appname
    ports:
      - "5432:5432"

  pgadmin:
    depends_on:
      - db
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  
  api-server:
    depends_on:
      - db
    container_name: api-server
    build: ./
    image: myapp
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/myapp
    ports:
      - 8000:8000